### ISSUE TITLE
Could not start application tzdata

### ISSUE THREAD

**Issue by tomasbasham** [lee-dohm/octokit.ex#3]
After creating a new elixir project and installing `octokit` as a dependency I am getting the following error:

```
Could not start application tzdata: exited in: Tzdata.App.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, Tzdata.EtsHolder, {%ArgumentError{message: "unknown application: :tzdata"}, [{Application, :app_dir, 1, [file: 'lib/application.ex', line: 428]}, {Application, :app_dir, 2, [file: 'lib/application.ex', line: 437]}, {Tzdata.EtsHolder, :release_dir, 0, [file: 'lib/tzdata/ets_holder.ex', line: 86]}, {Tzdata.EtsHolder, :make_sure_a_release_dir_exists, 0, [file: 'lib/tzdata/ets_holder.ex', line: 70]}, {Tzdata.EtsHolder, :make_sure_a_release_is_on_file, 0, [file: 'lib/tzdata/ets_holder.ex', line: 64]}, {Tzdata.EtsHolder, :init, 1, [file: 'lib/tzdata/ets_holder.ex', line: 10]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}}}
            (tzdata) lib/tzdata/tzdata_app.ex:15: Tzdata.App.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

It may very well be something I am doing wrong here. I have pushed my repo to https://github.com/tomasbasham/repo. Hopefully it is able to reproduce the problem.

**Comment by lee-dohm** [comment]
Which version of Elixir are you using?

**Comment by lee-dohm** [comment]
I did the following and could not reproduce it:

1. Cloned your repo
1. Ran `mix deps.get`
1. Ran `mix test`

I got a test failure, but no problem starting the applications. I'm running Elixir v1.4.2 on Mac OS X 10.12.3.

**Comment by tomasbasham** [comment]
I'm using the following setup:

 - Erlang/OTP 19
 - IEx 1.4.2
 - OS X 10.12.3

I should have mentioned I am building a command line application (if that was not clear) so am using `mix escript.build` to build the executable and running it is causing the error I have been seeing.

**Comment by lee-dohm** [comment]
When I follow your steps, I see the error you're describing. I'm not familiar with the new `escript` support in v1.4. I haven't played around with it yet. But when I use `iex -S mix` in your repo, I see the `tzdata` debug messages come up. So it would seem that things are configured properly at some level. Perhaps there is something extra you have to do with escripts to start the application tree?

**Comment by tomasbasham** [comment]
OK, thanks for looking into this. I'll post a solution here if I find it

**Comment by tomasbasham** [comment]
Found a solution. Apparently there is a known issue with tzdata and escript as you suggested. The current fix is to add the following to `deps` (as documented somewhere in this link https://github.com/bitwalker/timex/issues/86)

    {:tzdata, "== 0.1.8", override: true}

Thanks for your help to guide me down the right path

**Comment by lee-dohm** [comment]
You're welcome. I'm glad that you were able to find a solution! :grinning:
